services:
  web:
    build: .
    container_name: pyKasaWireLabel_web
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
